In [1]:
import os
os.chdir('/Users/layne/Desktop/pydatasci')
os.getcwd()

'/Users/layne/Desktop/pydatasci'

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import *

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import History

/Users/layne/.pyenv/versions/3.7.6/envs/jupyterlab/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [3]:
# ### ===================== DATASET SONAR (BINARY) =====================
# https://machinelearningmastery.com/binary-classification-tutorial-with-the-keras-deep-learning-library/

source = pd.read_csv("pydatasci/data/sonar.csv")
sonar_data = source.sample(frac=1)

x = sonar_data.drop("object", axis=1).values
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# target = sonar_data['R'].values
# encoder = LabelEncoder()
# encoder.fit(target)
# y = encoder.transform(target)

# testing multi-class on binary dataset
target = sonar_data['object']
y = pd.get_dummies(target, prefix='object').values
# we only need 1 column from this two column OHE'd array.
y = np.delete(y, 1, 1)

train_x, test_x, train_y, test_y = train_test_split(x_scaled, y, test_size=0.20)


model = Sequential(name='Sonar')
model.add(Dense(60, activation='relu', kernel_initializer='he_uniform')) # input_dim=60, <-- dropout
model.add(Dropout(0.15))
model.add(Dense(30, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(1, activation='sigmoid', kernel_initializer='glorot_uniform'))
model.compile(optimizer="RMSprop", loss='binary_crossentropy', metrics=['accuracy'])

model.fit(
    train_x, train_y
    , validation_data=(test_x, test_y)
    , verbose=0
    , batch_size=3, epochs=100
    , callbacks=[History()]
)
print(model.summary())

Model: "Sonar"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 60)                3660      
_________________________________________________________________
dropout (Dropout)            (None, 60)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 30)                1830      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 31        
Total params: 5,521
Trainable params: 5,521
Non-trainable params: 0
_________________________________________________________________
None


In [7]:
model.predict_classes(train_x)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
    

In [4]:
probs = model.predict(train_x)

In [5]:
preds = (model.predict(train_x) > 0.5).astype("int32")

In [5]:
preds = (model.predict(train_x) > 0.5).astype("int32")

In [7]:
metrics = model.evaluate(test_x, test_y, verbose=0)

In [11]:
str(type(metrics)) == "<class 'list'>"

True

In [12]:
isinstance(metrics, list)

True

---

In [6]:
accuracy_score(train_y, preds)

1.0

In [7]:
precision_score(train_y, preds, average='binary')

1.0

In [8]:
recall_score(train_y, preds, average='binary')

1.0

In [9]:
f1_score(train_y, preds, average='binary')

1.0

In [10]:
roc_auc_score(train_y, probs, average='micro')

1.0

---

In [75]:
roc_curve(train_y, probs)

(array([0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0.        , 0.92222222, 0.93333333, 0.95555556, 0.96666667,
        0.98888889, 1.        , 1.        ]),
 array([2.0000000e+00, 1.0000000e+00, 9.9999988e-01, 9.9999952e-01,
        9.9999946e-01, 9.9999934e-01, 9.9999845e-01, 9.3206930e-26],
       dtype=float32))

In [76]:
precision_recall_curve(train_y, probs)

(array([1., 1., 1., 1., 1., 1., 1.]),
 array([1.        , 0.98888889, 0.96666667, 0.95555556, 0.93333333,
        0.92222222, 0.        ]),
 array([0.99999845, 0.99999934, 0.99999946, 0.9999995 , 0.9999999 ,
        1.        ], dtype=float32))

In [77]:
confusion_matrix(train_y, preds)

array([[75,  0],
       [ 0, 90]])

---

In [119]:
model.history.history

{}

In [120]:
results = model.evaluate(train_x, train_y, verbose=0)

In [121]:
results

[1.0197285238433551e-09, 1.0]